// Mocks generated by Mockito 5.2.0 from annotations
// in magic/test/helpers/test_helpers.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:flutter/material.dart' as _i8;
import 'package:hive_flutter/hive_flutter.dart' as _i2;
import 'package:magic/core/enums/workout_status.dart' as _i5;
import 'package:magic/core/models/workout.dart' as _i3;
import 'package:magic/core/services/local_storage_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stacked_services/stacked_services.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeBox_0<E> extends _i1.Fake implements _i2.Box<E> {}

class _FakeWorkout_1 extends _i1.Fake implements _i3.Workout {}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i4.LocalStorageService {
  @override
  _i2.Box<_i3.Workout> get workoutBox =>
      (super.noSuchMethod(Invocation.getter(#workoutBox),
          returnValue: _FakeBox_0<_i3.Workout>()) as _i2.Box<_i3.Workout>);
  @override
  set workoutBox(_i2.Box<_i3.Workout>? _workoutBox) =>
      super.noSuchMethod(Invocation.setter(#workoutBox, _workoutBox),
          returnValueForMissingStub: null);
  @override
  int get selectedIndex =>
      (super.noSuchMethod(Invocation.getter(#selectedIndex), returnValue: 0)
          as int);
  @override
  set selectedIndex(int? _selectedIndex) =>
      super.noSuchMethod(Invocation.setter(#selectedIndex, _selectedIndex),
          returnValueForMissingStub: null);
  @override
  set workoutStatus(_i5.WorkoutStatus? _workoutStatus) =>
      super.noSuchMethod(Invocation.setter(#workoutStatus, _workoutStatus),
          returnValueForMissingStub: null);
  @override
  _i3.Workout getWorkOut() =>
      (super.noSuchMethod(Invocation.method(#getWorkOut, []),
          returnValue: _FakeWorkout_1()) as _i3.Workout);
  @override
  _i6.Future<bool> addWorkout(_i3.Workout? workout) =>
      (super.noSuchMethod(Invocation.method(#addWorkout, [workout]),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  _i6.Future<bool> deleteWorkout(int? index) =>
      (super.noSuchMethod(Invocation.method(#deleteWorkout, [index]),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  _i2.Box<_i3.Workout> getBox() =>
      (super.noSuchMethod(Invocation.method(#getBox, []),
          returnValue: _FakeBox_0<_i3.Workout>()) as _i2.Box<_i3.Workout>);
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i7.NavigationService {
  @override
  String get previousRoute =>
      (super.noSuchMethod(Invocation.getter(#previousRoute), returnValue: '')
          as String);
  @override
  String get currentRoute =>
      (super.noSuchMethod(Invocation.getter(#currentRoute), returnValue: '')
          as String);
  @override
  _i8.GlobalKey<_i8.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(Invocation.method(#nestedNavigationKey, [index]))
          as _i8.GlobalKey<_i8.NavigatorState>?);
  @override
  void config(
          {bool? enableLog,
          bool? defaultPopGesture,
          bool? defaultOpaqueRoute,
          Duration? defaultDurationTransition,
          bool? defaultGlobalState,
          _i7.Transition? defaultTransitionStyle,
          String? defaultTransition}) =>
      super.noSuchMethod(
          Invocation.method(#config, [], {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition
          }),
          returnValueForMissingStub: null);
  @override
  _i6.Future<T?>? navigateWithTransition<T>(_i8.Widget? page,
          {bool? opaque,
          String? transition = r'',
          Duration? duration,
          bool? popGesture,
          int? id,
          _i8.Curve? curve,
          bool? fullscreenDialog = false,
          bool? preventDuplicates = true,
          _i7.Transition? transitionClass,
          _i7.Transition? transitionStyle}) =>
      (super.noSuchMethod(Invocation.method(#navigateWithTransition, [
        page
      ], {
        #opaque: opaque,
        #transition: transition,
        #duration: duration,
        #popGesture: popGesture,
        #id: id,
        #curve: curve,
        #fullscreenDialog: fullscreenDialog,
        #preventDuplicates: preventDuplicates,
        #transitionClass: transitionClass,
        #transitionStyle: transitionStyle
      })) as _i6.Future<T?>?);
  @override
  _i6.Future<T?>? replaceWithTransition<T>(_i8.Widget? page,
          {bool? opaque,
          String? transition = r'',
          Duration? duration,
          bool? popGesture,
          int? id,
          _i8.Curve? curve,
          bool? fullscreenDialog = false,
          bool? preventDuplicates = true,
          _i7.Transition? transitionClass,
          _i7.Transition? transitionStyle}) =>
      (super.noSuchMethod(Invocation.method(#replaceWithTransition, [
        page
      ], {
        #opaque: opaque,
        #transition: transition,
        #duration: duration,
        #popGesture: popGesture,
        #id: id,
        #curve: curve,
        #fullscreenDialog: fullscreenDialog,
        #preventDuplicates: preventDuplicates,
        #transitionClass: transitionClass,
        #transitionStyle: transitionStyle
      })) as _i6.Future<T?>?);
  @override
  bool back<T>({dynamic result, int? id}) => (super.noSuchMethod(
      Invocation.method(#back, [], {#result: result, #id: id}),
      returnValue: false) as bool);
  @override
  void popUntil(_i8.RoutePredicate? predicate) =>
      super.noSuchMethod(Invocation.method(#popUntil, [predicate]),
          returnValueForMissingStub: null);
  @override
  void popRepeated(int? popTimes) =>
      super.noSuchMethod(Invocation.method(#popRepeated, [popTimes]),
          returnValueForMissingStub: null);
  @override
  _i6.Future<T?>? navigateTo<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#navigateTo, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i6.Future<T?>?);
  @override
  _i6.Future<T?>? navigateToView<T>(_i8.Widget? view,
          {dynamic arguments,
          int? id,
          bool? opaque,
          _i8.Curve? curve,
          Duration? duration,
          bool? fullscreenDialog = false,
          bool? popGesture,
          bool? preventDuplicates = true,
          _i7.Transition? transition,
          _i7.Transition? transitionStyle}) =>
      (super.noSuchMethod(Invocation.method(#navigateToView, [
        view
      ], {
        #arguments: arguments,
        #id: id,
        #opaque: opaque,
        #curve: curve,
        #duration: duration,
        #fullscreenDialog: fullscreenDialog,
        #popGesture: popGesture,
        #preventDuplicates: preventDuplicates,
        #transition: transition,
        #transitionStyle: transitionStyle
      })) as _i6.Future<T?>?);
  @override
  _i6.Future<T?>? replaceWith<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#replaceWith, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i6.Future<T?>?);
  @override
  _i6.Future<T?>? clearStackAndShow<T>(String? routeName,
          {dynamic arguments, int? id, Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#clearStackAndShow, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #parameters: parameters
      })) as _i6.Future<T?>?);
  @override
  _i6.Future<T?>? clearTillFirstAndShow<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#clearTillFirstAndShow, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i6.Future<T?>?);
  @override
  _i6.Future<T?>? clearTillFirstAndShowView<T>(_i8.Widget? view,
          {dynamic arguments, int? id}) =>
      (super.noSuchMethod(Invocation.method(#clearTillFirstAndShowView, [view],
          {#arguments: arguments, #id: id})) as _i6.Future<T?>?);
  @override
  _i6.Future<T?>? pushNamedAndRemoveUntil<T>(String? routeName,
          {_i8.RoutePredicate? predicate, dynamic arguments, int? id}) =>
      (super.noSuchMethod(Invocation.method(#pushNamedAndRemoveUntil, [
        routeName
      ], {
        #predicate: predicate,
        #arguments: arguments,
        #id: id
      })) as _i6.Future<T?>?);
}
